#!/bin/sh

export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
unsetopt PROMPT_SP

export TERM="st"
export EDITOR="vim"
export BROWSER="chromium --force-dark-mode"

export XDG_RUNTIME_DIR=/run/user/$(id -u)
export XINITRC="$XDG_CONFIG_HOME"/xinitrc
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export GOPATH="$XDG_DATA_HOME"/go
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc

tabs -4
