#!/bin/sh
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# Setting NVIDIA on for Optimus laptops
# xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --setprovideroutputsource Intel Intel
xrandr --auto
xrandr --dpi 96

# Other things
dbus-update-activation-environment --systemd DISPLAY
export SSH_AUTH_SOCK
export XDG_SESSION_TYPE=X11
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_STYLE_OVERRIDE=kvantum

# Start programs
dwmblocks &
/usr/bin/pipewire &
/usr/bin/pipewire-pulse &
/usr/bin/wireplumber &
nm-applet &
[ grep -v /sys/class/power_supply/BAT0/status "Discharging" ] && xcompmgr &
hsetroot -fill ~/.local/share/backgrounds/field.jpg &
exec dwm

